version: 2.1
jobs:
  zaliczenie:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  zlaiczenie-workflow:
    jobs:
      - zaliczenie